language: go
go:
- 1.12
env:
- GO111MODULE=on
script: go vet
before_deploy:
- "./build.sh"
deploy:
  provider: releases
  api_key:
    secure: Q9ThUhv8RkQPLMVLcwCHBZTeB245XKVtH0j0N6SQ/VZ1JR31HBg/qBQSJKn9vI/5aaholHXr6728He5tHoltuXiEc2C/kh6zPfdUYmAXs0msh+qT6IyLV+bgh2a5aNwzscHzBGqpj2bUve9nmzsR4DHhkUt3KrC2eGxgWro2UilewNSkINGWo5+Rp79UEBgzWEbh8V3QXVVQjjgnoQ1HvKGxhoOECiefrp0kzQ/5Ud6PzPl3xCIhRs64GB8dZUZJPh+vSf9qBfRJ67V8ofHezi56RFi+eNIlhEi2JY2NSWbFaoTXBe8dsROvCz7ELEOj4gVC6MCxpsnvJHKujScqUuaNYrm+aa1mwnZ5JpRznEhsSflFCn+jXKshv40FfIk5K+4n1KFZUvUuqtjmLZiJkPaQDDZzPJL6dA4nQ6AH6+t2S5mKsHKZ+lyYJ8p68rRdKwl/B0T+bXZ7nK2LsqDFw0nE84rwgOyUog2stHLqXDKUNDcw1KcNTW8bQMDRqaueayzGTob5hkRmguLvcpI6fEeJUOSq7HTv1gItnrU67w2hNKVTXqVxP4p2Kk0yfjQwOUtJR8ETnKA6roLv01bL+HMLW15JvvJ3C8JVwingRLFb8TCfTdV9JZssQgk6NajSDswj7sXEvzlZ9POqOVtjH93o+5mSttB/h8LNxVOK4aY=
  skip_cleanup: true
  file:
    - release/pve_exporter-linux-amd64
    - release/pve_exporter-linux-amd64.sha256
  on:
    repo: wakeful/pve_exporter
    branch: master
    tags: true
